SET IDENTITY_INSERT [dbo].[Fish] ON
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (11, 0, 0, N'Copperband Butterfly', N'Chelmon Rostratus', N'Copperband Butterfly, Chelmon Rostratus', <SQLVARIANT>, N'FishOfHex', NULL, N'65', NULL, NULL, NULL, 0, 8, 10, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (12, 7, 0, N'Common Clown Fish', N'Amphiprion Ocellaris', N'Common Clown Fish, Amphiprion Ocellaris', <Binary Data>, N'FishOfHex', NULL, N'25', NULL, NULL, NULL, 0, 0, 3, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (13, 14, 0, N'Foxface fish', N'Siganus vulpinus', N'The Foxface Lo, also known as the Foxface Rabbitfish, has a very unique body color. It has a mottled yellow-brown body with a dark chest. The face is very light in color and speckled on the lower half.  They are a very hardy fish, and are great additions to the newly-established tank. It may reside in a 200 litre or larger aquarium. It is a very peaceful species except when housed with other rabbitfish. The Foxface Lo may be housed with more aggressive fish.  Its predators will tend to leave it alone because of its venomous dorsal spines. Rabbitfish are generally reef-safe if they are well fed. If not, it is possible for them to nip at and consume some species of LPS and soft corals.  The Foxface Lo diet consists of a variety of fresh vegetables and undesirable species of algae. It does nip and possibly eat some soft and hard coral polyps.', <SQLVARIANT>, NULL, NULL, N'65', NULL, NULL, NULL, 0, 0, 4, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (22, 0, 0, N'6679', N'67967', N'69679', <SQLVARIANT>, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (23, 0, 0, N'1aaaaa', N'sdsd', N'222222222122121212', <SQLVARIANT>, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (24, 0, 0, N'222222', N'ffff', N'fffffff', <SQLVARIANT>, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (25, 0, 0, N'aaaaaa', N'sdsd', N'aaaaaaaaaaaa', <SQLVARIANT>, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (26, 0, 0, N'1aaaaa', N'sdsd', N'aaaaaaaaaaaa', <SQLVARIANT>, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (27, 0, 0, N'aaaaaa', N'sdsd', N'aaaaaaaaaaaa', <SQLVARIANT>, N'FishOfHex', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (28, 0, 0, N'aaaaaa', N'sdsd', N'fffffff', <SQLVARIANT>, N'FishOfHex', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (29, 0, 0, N'aaaaaa', N'sdsd', N'aaaaaaaaaaaa', <SQLVARIANT>, N'8ff69de3-db77-4512-9ac0-6b0716655b6e', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, NULL)
INSERT INTO [dbo].[Fish] ([FishId], [Type], [TankSize], [Name], [ScientificName], [Details], [Photo], [UploadedBy], [UploadedOn], [Price], [Size], [FishSize], [CommentId], [Likes], [DisLikes], [Views], [SoldOut], [FishAvailable], [FishAvailableFrom]) VALUES (30, 0, 0, N'aaaaaa', N'sdsd', N'aaaaaaaaaaaa', <SQLVARIANT>, N'FishOfHex', NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 0, NULL)
SET IDENTITY_INSERT [dbo].[Fish] OFF
