//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string CommentId { get; set; }
        public int Type { get; set; }
        public string UserId { get; set; }
        public string CreatedOn { get; set; }
        public string RemovedOn { get; set; }
        public string CommentOn { get; set; }
        public string CommentTitle { get; set; }
        public string CommentText { get; set; }
        public int CommentViews { get; set; }
        public bool Removed { get; set; }
        public int Reports { get; set; }
        public int Likes { get; set; }
        public int DisLikes { get; set; }
    }
}
