//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoralConnection
    {
        public int ConnectionId { get; set; }
        public int CoralId { get; set; }
        public string UserId { get; set; }
        public string CreatedOn { get; set; }
        public string RemovedOn { get; set; }
        public bool Removed { get; set; }
        public string FragTo { get; set; }
        public string FragFrom { get; set; }
        public string ColonyTo { get; set; }
        public string ColonyFrom { get; set; }
    }
}
