//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coral
    {
        public int CoralId { get; set; }
        public int Type { get; set; }
        public int Light { get; set; }
        public int Flow { get; set; }
        public int Food { get; set; }
        public int Growth { get; set; }
        public string Name { get; set; }
        public string ScientificName { get; set; }
        public string Details { get; set; }
        public byte[] Photo { get; set; }
        public string UploadedBy { get; set; }
        public string UploadedOn { get; set; }
        public string Price { get; set; }
        public string Size { get; set; }
        public string FragSize { get; set; }
        public string CommentId { get; set; }
        public int Likes { get; set; }
        public int DisLikes { get; set; }
        public int Views { get; set; }
        public bool SoldOut { get; set; }
        public bool FragAvailable { get; set; }
        public string FragAvailableFrom { get; set; }
    }
}
